rate: 50
timeout:
  press: 0.1
  sequence: 0.2

presets:
  change_state:
    trigger: [[LSP, RSP], 1]
    action:
      - type: shared_values
        method: round_robin
        key: state
        values: ['chassis', 'arm']
