joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Control
joint1_position_controller:
  type: position_controllers/JointPositionController
  joint: joint1
  pid: {p: 80.0, i: 0.3, d: 3.0}
joint2_position_controller:
  type: position_controllers/JointPositionController
  joint: joint2
  pid: {p: 80.0, i: 0.2, d: 4.0}
joint3_position_controller:
  type: position_controllers/JointPositionController
  joint: joint3
  pid: {p: 30.0, i: 0.2, d: 4.0}
joint4_position_controller:
  type: position_controllers/JointPositionController
  joint: joint4
  pid: {p: 25.0, i: 0.1, d: 3.0}
joint5_position_controller:
  type: position_controllers/JointPositionController
  joint: joint5
  pid: {p: 25.0, i: 0.2, d: 1.0}
joint6_position_controller:
  type: position_controllers/JointPositionController
  joint: joint6
  pid: {p: 10.0, i: 0.1, d: 1.0}
joint7_position_controller:
  type: position_controllers/JointPositionController
  joint: joint7
  pid: {p: 10.0, i: 0.1, d: 1.0}
